version: "3.9"
services:
  kali:
    build: ./
    image: kali
    ports:
      - ${NOVNCPORT}:${NOVNCPORT}
    restart: always
    volumes:
      - type: bind
        source: ${MOUNT_PATH}
        target: /tmp/local_mount
    environment:
      - MOUNT_PATH
      - USER
      - VNCPORT
      - VNCPWD
      - VNCDISPLAY
      - VNCDEPTH
      - NOVNCPORT
      - DEBIAN_FRONTEND
    command: ./entrypoint.sh 
    tty: true
    stdin_open: true